apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnet-nov11-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnet-nov11-test 
  name: cnet-nov11-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnet-nov11-test 
